[package]
name = "new-contract-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.new-contract]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.33.0"
